/**
 * Design tokens for Heritage Voyager.
 *
 * The type ramp and spacing are the Stitch prototype's. The palette is not:
 * the prototype's surfaces were a blue-tinted white, and this atlas is meant
 * to read as paper — warm cream, aged gold, and ink rather than black.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#5f5748',
        'on-primary-fixed-variant': '#5a5140',
        'on-secondary-fixed': '#221e17',
        'on-tertiary-fixed': '#2a1d00',
        'surface-container-highest': '#dbcfb6',
        'inverse-primary': '#d8caa9',
        primary: '#211d17',
        'primary-fixed': '#efe6d2',
        'on-secondary': '#fffdf7',
        'on-secondary-fixed-variant': '#4d463a',
        'tertiary-fixed-dim': '#c9a227',
        outline: '#8d8271',
        'on-primary-container': '#9a8f78',
        secondary: '#6a6152',
        'primary-fixed-dim': '#d8caa9',
        'error-container': '#f5ddd6',
        'on-tertiary-container': '#a1832f',
        'on-error-container': '#7a2418',
        'on-tertiary-fixed-variant': '#5d4602',
        'on-primary': '#fffdf7',
        'tertiary-container': '#2b2113',
        'on-primary-fixed': '#241f18',
        'outline-variant': '#cdc2ac',
        'secondary-container': '#e7dfcd',
        surface: '#f7f2e8',
        'surface-container-high': '#e3d9c5',
        'tertiary-fixed': '#f2dfb2',
        background: '#f7f2e8',
        'on-background': '#2b2620',
        'surface-container-lowest': '#fffdf7',
        'inverse-surface': '#2b2620',
        'on-surface': '#2b2620',
        'on-surface-variant': '#5c5347',
        'inverse-on-surface': '#f7f2e8',
        'surface-container-low': '#f3ede0',
        'surface-tint': '#8a7c62',
        'surface-variant': '#e9e1d1',
        'surface-container': '#ebe3d3',
        'secondary-fixed-dim': '#cec4ad',
        'surface-bright': '#fcf9f2',
        'surface-dim': '#e2d8c4',
        error: '#9d3427',
        tertiary: '#8a6a1f',
        'on-error': '#fffdf7',
        'on-tertiary': '#fffdf7',
        'secondary-fixed': '#e9e1cf',
        'primary-container': '#2b2620',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1200px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'margin-desktop': '64px',
        'stack-lg': '48px',
        'margin-mobile': '20px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'stat-display': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
        'body-lg': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'stat-display': ['32px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
};
