/**
 * Design tokens transcribed from the Stitch prototype.
 * Nothing here is invented — the palette, spacing scale and type ramp all come
 * from the prototype's inline `tailwind.config`.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#63635f',
        'on-primary-fixed-variant': '#39475f',
        'on-secondary-fixed': '#1b1c19',
        'on-tertiary-fixed': '#261900',
        'surface-container-highest': '#d8e3fa',
        'inverse-primary': '#b9c7e4',
        primary: '#000000',
        'primary-fixed': '#d6e3ff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#474744',
        'tertiary-fixed-dim': '#e9c176',
        outline: '#75777e',
        'on-primary-container': '#76849f',
        secondary: '#5e5e5b',
        'primary-fixed-dim': '#b9c7e4',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#a17f3b',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#5d4201',
        'on-primary': '#ffffff',
        'tertiary-container': '#261900',
        'on-primary-fixed': '#0d1c32',
        'outline-variant': '#c5c6cd',
        'secondary-container': '#e1dfdb',
        surface: '#f9f9ff',
        'surface-container-high': '#dee8ff',
        'tertiary-fixed': '#ffdea5',
        background: '#f9f9ff',
        'on-background': '#111c2c',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#263142',
        'on-surface': '#111c2c',
        'on-surface-variant': '#44474d',
        'inverse-on-surface': '#ebf1ff',
        'surface-container-low': '#f0f3ff',
        'surface-tint': '#515f78',
        'surface-variant': '#d8e3fa',
        'surface-container': '#e7eeff',
        'secondary-fixed-dim': '#c8c6c2',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#cfdaf1',
        error: '#ba1a1a',
        tertiary: '#000000',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e4e2dd',
        'primary-container': '#0d1c32',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1200px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'margin-desktop': '64px',
        'stack-lg': '48px',
        'margin-mobile': '20px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'stat-display': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
        'body-lg': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'stat-display': ['32px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
};
